### PR TITLE
feat: add a Google Tag Manager loader

### PR DESCRIPTION
**Pull request by dcoa**
**Description**
This PR create a loader function in the component footer to add GTM scripts into the MFE. 

This PR is a simplified version of the upstream proposal https://github.com/openedx/frontend-platform/pull/631 

**How to test**

1. Create a new environment and integrate the current footer in the MFEs.
2. Configure the loader with `GOOGLE_TAG_MANAGER_ID` and `GOOGLE_TAG_MANAGER_ENVIRONMENT`, as the example: 
```python
MFE_CONFIG["GOOGLE_TAG_MANAGER_ID"]="GTM-WHZV2TB"
MFE_CONFIG["GOOGLE_TAG_MANAGER_ENVIRONMENT"]="&gtm_auth=hufwZYrqT6ksy4j52734fw&gtm_preview=env-83&gtm_cookies_win=x"
```
4. Go to the browser and inspect the html to check the scripts loaded.

### CODE REVIEW

**Comment by igobranco** [comment]
@dcoa 
I started up the tutor dev with your PR footer, but the learning MFE didn't startup, the browser console shows this error: 
```
Module configuration error: GOOGLE_TAG_MANAGER_ID is required by ProcessEnvConfigService
Module configuration error: GOOGLE_TAG_MANAGER_ENVIRONMENT is required by ProcessEnvConfigService.
```

I double checked that the mfe_config API for the learning MFE is returning the right configurations:
http://apps.test06.nau.fccn.pt:2000/api/mfe_config/v1?mfe=learning
```json
{
....
    "GOOGLE_TAG_MANAGER_ID": "GTM-WHZV2TB",
    "GOOGLE_TAG_MANAGER_ENVIRONMENT": "&gtm_auth=hufwZYrqT6ksy4j52734fw&gtm_preview=env-83&gtm_cookies_win=x",
....
}
```

Additionally can you rebase with the latest commits?

**Comment by dcoa** [comment]
I made the changes could you try again? @igobranco

**Comment by igobranco** [comment]
@dcoa  what changes? Now I don't see it the console error, but it still not working. Are you really loading the GTM JS? Are you seeing any UI change on the right lower side of the screen?
I'm seeing a couple of warning on the console, with its stacktrace, but the spinner never ends... when I checkout the `nau/redwood.master` branch the webpack recompiles and the MFE works. When I checkout this PR branch it won't work.

**Comment by dcoa** [comment]
@igobranco  could you try one more time?, thanks.

Screenshot from 2024-11-13 11-28-55

**Review by igobranco — APPROVED** [review]
@dcoa LGTM ✔️ 
I have confirmed that GTM is loading!
I had to apply some configuration changes on GTM triggers configuration to load the external libraries: CookieScript and our Vasco Chatbot. So they can be loaded using any tutor local URL/domain.
image

**Pull request merged**
