### PR TITLE
feat(redwood): add nau learning footer customization

### PR DESCRIPTION
**Pull request by dcoa**
This PR migrates the custom NAU footer changes to the Redwood version. 

image

**How to test**

1. Create a tutor redwood environment.
2.  Inside your environment clone the learning MFE and mount it with `tutor mounts add ./frontend-app-learning`.
3. Inside the learning MFE, clone the footer repository with the current branch (remember to run `npm install` for both, the learning app and the footer).
4. Create the `module.config.js` file and add the following configuration.
```javascript
module.exports = {
  localModules: [
    { moduleName: '@edx/frontend-component-footer/dist', dir: './frontend-component-footer-nau', dist: 'src' },
    { moduleName: '@edx/frontend-component-footer', dir: './frontend-component-footer-nau', dist: 'src' },
  ],
};
```
3. Run the command `tutor images build learning-dev`.
4. Start your environment `tutor dev start`.
5. Create a course and configure the organization info inside the LMS admin.
6. Open the courseware and check you can see the changes.

### CODE REVIEW

**Comment by dcoa** [comment]
Hi @sandroscosta have you been able to review this PR? Do you have any issues that should be addressed?

**Comment by sandroscosta** [comment]
@dcoa I'm pushing a refactor to help with footer configuration. I'll review everything after.

**Review by sandroscosta — APPROVED** [review]
Tested and refactored. Everything looks good.

**Comment by dcoa** [comment]
Thank you  @sandroscosta, feel free to merge the PR at any time.

**Pull request merged**
